services:
  jobmanager:
    build: .
    ports:
      - "8081:8081"
    command: jobmanager
    expose:
      - "6123"
    depends_on:
      - kafka
      - postgres
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build: .
    depends_on:
      - jobmanager
    command: taskmanager
    expose:
      - "6121"
      - "6122"
    scale: 1
    links:
      - jobmanager:jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2


  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka:/var/lib/kafka/data

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ethereum
      POSTGRES_USER: ethereum
      POSTGRES_PASSWORD: ethereum
    volumes:
      - postgres:/var/lib/postgresql/data

  datagen:
    build: producer/
    depends_on:
      - kafka
    profiles:
      - datagen

volumes:
  kafka:
  postgres: